### PR TITLE
Adding more technical blocks to blacklist

### PR DESCRIPTION
**Pull request by mathias-github**
I've added a few more technical blocks, that crash the client, to the blacklist.

Some doors used E_ITEM instead of E_BLOCK, which resulted in the door items getting blocked instead of the door blocks. This is fixed now.

I removed Lit Furnace and Farmland from the list, since these blocks don't crash the client in either version 1.7 or 1.8.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Could you squash the commits into a single one? Thanks.

**Comment by mathias-github** [comment]
This one can be closed.

**Comment by madmaxoft** [comment]
Why is that? Are the blocks legal?

**Comment by mathias-github** [comment]
I already created a pull request with a single commit, which was merged.

**Pull request closed without merging**
