### PR TITLE
changed colorcode indicator to new indicator

### PR DESCRIPTION
**Pull request by SphinxC0re**
From @ to §
I don't know if I did that right.
The change is based on the information on this site: 
http://minecraft.gamepedia.com/Formatting_codes

### CODE REVIEW

**Comment by NiLSPACE** [comment]
When it was implemented we used `@` because not all people can use `§` from their keyboard.

**Comment by madmaxoft** [comment]
Not only that, but `§` is not in base ascii, so it needs some kind of encoding, usually utf-8; this might create problems when editing the source file in various external editors.

I think a better change would be to use `&` as the colorcode indicator; as far as I know it is the character used by most servers.

Also, update the comments around the changed code so that they make sense after the change. They still mention `@`.

**Comment by SphinxC0re** [comment]
I did some research and the § is not even the right thing for the MOTD. the MOTD uses a unicode char for encoding: http://minecraft.gamepedia.com/Formatting_codes#Use_in_server.properties_and_pack.mcmeta

**Comment by madmaxoft** [comment]
Actually, `\u00A7` is `§`; but most likely the java server has an encoding problem with the file, exactly as I mentioned.

**Pull request closed without merging**
