### PR TITLE
You can now use @ properly in the motd

### PR DESCRIPTION
**Pull request by NiLSPACE**
When using @@ you get a single @

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Why didn't you use a regular escape char? like \

**Comment by NiLSPACE** [comment]
*because it would be harder to implement* ;)

**Comment by SphinxC0re** [comment]
it is one char to change

**Comment by bearbin** [comment]
since @ is already used as an escape char then using it again would make sense, right?

**Comment by SphinxC0re** [comment]
Okay, but it has to be documented properly

**Comment by NiLSPACE** [comment]
Well, where **could** we document it? We don't have any documentation for Core.

**Comment by SphinxC0re** [comment]
In the [Wiki](http://wiki.mc-server.org)

**Comment by s32ialx** [comment]
You rock thanks for this nice addition!

**Comment by NiLSPACE** [comment]
No problem :)

**Comment by SafwatHalaby** [comment]
Just a side note: I noticed that after this merge, when switching from Master to Testing, I always get this message: `M	MCServer/Plugins/Core`, it will stay there until I do a `git submodule update`.

I honestly don't know what that means because my understanding of submodules is nill. Just thought I should mention it.

**Comment by SphinxC0re** [comment]
When you do a checkout on the same branch you are currently on, got reset this branch to the *unmodified* state. So the data is probably lost. That's the only thing I can think of right now

**Comment by worktycho** [comment]
@SafwatHalaby Its because git submodules aren't properly integrated into git, so when you checkout a different branch it doesn't update the submodules. the message is just telling you that the checked out submodule is different from what git thinks is should be for this branch, because it wasn't updated when you switched branch.

**Comment by SafwatHalaby** [comment]
So, we should merge the changes with Testing as well?

**Comment by worktycho** [comment]
@SafwatHalaby No just accept that you have to run git submodule update after switching branches.

**Comment by SafwatHalaby** [comment]
Ok.

**Pull request merged**
